version: "3"

services:
  backend:
    env_file: .env
    build: ./server
    image: presto-analytics:dev
    depends_on:
      - postgres
    ports:
      - "3333:3333"
      - "9229:9229"
    volumes:
      - ./:/app
  postgres:
    env_file: .env
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql

volumes:
  db-volume:
