version: "3"

services:
  backend:
    env_file: .env
    build: ./server
    image: pa-backend:dev
    depends_on:
      - postgres
    expose:
      - ${PORT}
      - "9229"
    ports:
      - ${PORT}:${PORT}
      - "9229:9229"
    volumes:
      - ./server:/opt/backend

  # front-end:
  #   env_file: .env
  #   build: ./fe
  #   image: pa-frontend:dev
  #   expose:
  #     - ${CLIENT_PORT}
  #     - "35729"
  #   ports:
  #     - ${CLIENT_PORT}:${CLIENT_PORT}
  #     - "35729:35729"
  #   volumes:
  #     - ./fe:/app
  #   links:
  #     - backend

  postgres:
    env_file: .env
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql

volumes:
  db-volume:
