version: "3"

services:
  backend:
    env_file: .env
    build: ./server
    image: pa-backend:dev
    depends_on:
      - postgres
    expose:
      - ${SERVER_PORT}
      - "9229"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9229:9229"
    volumes:
      - ./server:/opt/backend

  app:
    env_file: .env
    build: ./client
    image: pa-frontend:dev
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client:/opt/app
    links:
      - backend

  postgres:
    env_file: .env
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql

volumes:
  db-volume:
