version: "3"

services:
  backend:
    env_file: .env
    build: ./
    image: pa-backend:dev
    depends_on:
      - postgres
    expose:
      - ${PORT}
      - "9229"
      - "35729"
    ports:
      - ${PORT}:${PORT}
      - "9229:9229"
      - "35729:35729"
    volumes:
      - ./:/opt/

  postgres:
    env_file: .env
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql

volumes:
  db-volume:
